# Simple package

name: dadjoke
parent: default

matches:
  - trigger: ":dadjoke"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "curl -H 'Accept: text/plain' https://icanhazdadjoke.com/"
          shell: wsl
